ccxt: check if 'amount' field is set for the order
Some exchanges don't set 'amount' for the order object.
This causes crash in ccxt store code:
  File "backtrader\stores\ccxtstore.py", line 39, in __init__
    self.size = float(ccxt_order['amount'])
TypeError: float() argument must be a string or a number, not 'NoneType'

Added check for 'amount' to be present in the order before checking it.

Signed-off-by: Ed Bartosh <bartosh@gmail.com>