Revert "minor fix on load_ticks"
This commit caused ccxt feed code to crash with
ValueError: invalid literal for int() with base 10

reverting

This reverts commit bf5407c417dee1b1bab000aa2164992cfaeb7187.

Fixes: #20